apiVersion: v1
kind: Secret
metadata:
  name: {{ include "polygon-monitor-app.fullname" . }}-secret
  labels:
    {{- include "polygon-monitor-app.labels" . | nindent 4 }}
type: Opaque
data:
  POLYGONSCAN_API_KEY: {{ .Values.secrets.polygonscanApiKey | b64enc }}
