apiVersion: v1
kind: Service
metadata:
  name: {{ include "polygon-monitor-app.fullname" . }}
  labels:
    {{- include "polygon-monitor-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }} # External port of the service
      targetPort: http # Refers to the 'name: http' in the deployment's container spec
      protocol: TCP
      name: http # Name of this service port
  selector:
    {{- include "polygon-monitor-app.selectorLabels" . | nindent 4 }}
