{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default (include "polygon-monitor-app.serviceAccountName" .) }} # Ensure this resolves to "polygon-monitor-app-ksa"
  labels:
    {{- include "polygon-monitor-app.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }} # This is where iam.gke.io/gcp-service-account will go
  {{- end }}
{{- end }}
